# Prueba de la clase Datos

__Autores:__ 
* David Cabornero Pascual
* Mario García Pascual

En este notebook comprobamos la clase Datos. Para ello, cargamos las bases de datos que vamos a usar en la asignatura y luego imprimimos las variables internas que hemos definido: datos, nominalAtributos y diccionario.

In [2]:
from Datos import Datos, isNominal, encodeAtribute

path1 = 'tic-tac-toe.data'
path2 = 'german.data'

datos1 = Datos(path1)
datos2 = Datos(path2)

Procedemos a mostrar el array nominalAtributos de los dos datasets, donde se muestra si cada columna contiene datos nominales o no

In [3]:
print('Tic Tac Toe:')
print(datos1.nominalAtributos)
print('German:')
print(datos2.nominalAtributos)

Tic Tac Toe:
[True, True, True, True, True, True, True, True, True, True]
German:
[True, False, True, True, False, True, True, False, True, True, False, True, False, True, True, False, True, False, True, True, False]


Ahora, mostramos el conjunto de datos en forma de array de numPy

In [4]:
print('Tic Tac Toe:')
print(datos1.datos)
print('German:')
print(datos2.datos)

Tic Tac Toe:
[[2 2 2 ... 1 1 1]
 [2 2 2 ... 2 1 1]
 [2 2 2 ... 1 2 1]
 ...
 [1 2 1 ... 1 2 0]
 [1 2 1 ... 1 2 0]
 [1 1 2 ... 2 2 0]]
German:
[[0 6 4 ... 1 0 1]
 [1 48 2 ... 0 0 2]
 [3 12 4 ... 0 0 1]
 ...
 [3 12 2 ... 0 0 1]
 [0 45 2 ... 1 0 2]
 [1 45 4 ... 0 0 1]]


Por último mostramos el contenido de los diccionarios.

In [5]:
print('Tic Tac Toe:')
print(datos1.diccionario)
print('German:')
print(datos2.diccionario)

Tic Tac Toe:
[{'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'b': 0, 'o': 1, 'x': 2}, {'negative': 0, 'positive': 1}]
German:
[{'A11': 0, 'A12': 1, 'A13': 2, 'A14': 3}, {}, {'A30': 0, 'A31': 1, 'A32': 2, 'A33': 3, 'A34': 4}, {'A40': 0, 'A41': 1, 'A410': 2, 'A42': 3, 'A43': 4, 'A44': 5, 'A45': 6, 'A46': 7, 'A48': 8, 'A49': 9}, {}, {'A61': 0, 'A62': 1, 'A63': 2, 'A64': 3, 'A65': 4}, {'A71': 0, 'A72': 1, 'A73': 2, 'A74': 3, 'A75': 4}, {}, {'A91': 0, 'A92': 1, 'A93': 2, 'A94': 3}, {'A101': 0, 'A102': 1, 'A103': 2}, {}, {'A121': 0, 'A122': 1, 'A123': 2, 'A124': 3}, {}, {'A141': 0, 'A142': 1, 'A143': 2}, {'A151': 0, 'A152': 1, 'A153': 2}, {}, {'A171': 0, 'A172': 1, 'A173': 2, 'A174': 3}, {}, {'A191': 0, 'A192': 1}, {'A201': 0, 'A202': 1}, {}]


Se puede comprobar que todos los datos se han cargado correctamente y que nominalAtributos y diccionario muestran lo que tienen que mostrar.

Ahora comprobaremos que las excepciones funcionan correctamente. Para ello hemos modificado la base de datos tic-tac-toe.data que tenga un atributo de tipo bool, por el cual debería saltarnos una excepción.

In [7]:
# NO EJECUTAR: LA BASE DE DATOS UTILIZADA HA SIDO MODIFICADA MANUALMENTE
path3 = 'tic-tac-toe2.data'

datos3 = Datos(path3)


ValueError: Error: introducido valor distinto de entero o nominal

Para implementar la clase Datos hemos utilizado dos funciones auxiliares que se encargan de hacer todo el trabajo. 

* <b>isNominal</b> devuelve True si el tipo de dato es nominal; False si es integer o float (numérico); lanza excepción en cualquier otro caso.

* __encodeAtribute__ recibe una lista de datos nominal y los ordena lexicográficamente y los codifica en números enteros.

isNominal está comprobada arriba. Ahora probamos encodeAtribute:

In [8]:
import numpy as np

a = np.array(['hola', 'que', 'tal', 'mundo', '!'])
print(encodeAtribute(a))

{'!': 0, 'hola': 1, 'mundo': 2, 'que': 3, 'tal': 4}


Vemos que devuelve un diccionario con los valores correctos.