In [1]:
import numpy as np
from Clasificador import ClasificadorNaiveBayes
from Datos import Datos

data = Datos('tic-tac-toe.data')
print(data.datos)
cl = ClasificadorNaiveBayes()

#Prueba de error
#print(cl.error(data.datos,2*np.ones(data.datos.shape[0])))

#Prueba de entrenamiento
cl.entrenamiento(data.datos,data.nominalAtributos,data.diccionario)
print(cl.entrenamientoAux)

[[2 2 2 ... 1 1 1]
 [2 2 2 ... 2 1 1]
 [2 2 2 ... 1 2 1]
 ...
 [1 2 1 ... 1 2 0]
 [1 2 1 ... 1 2 0]
 [1 1 2 ... 2 2 0]]
[array([[0.065762  , 0.14822547],
       [0.15240084, 0.19728601],
       [0.12839248, 0.30793319]]), array([[0.08141962, 0.17954071],
       [0.10542797, 0.23903967],
       [0.15970772, 0.2348643 ]]), array([[0.065762  , 0.14822547],
       [0.15240084, 0.19728601],
       [0.12839248, 0.30793319]]), array([[0.08141962, 0.17954071],
       [0.10542797, 0.23903967],
       [0.15970772, 0.2348643 ]]), array([[0.05010438, 0.11691023],
       [0.20041754, 0.15448852],
       [0.0960334 , 0.38204593]]), array([[0.08141962, 0.17954071],
       [0.10542797, 0.23903967],
       [0.15970772, 0.2348643 ]]), array([[0.065762  , 0.14822547],
       [0.15240084, 0.19728601],
       [0.12839248, 0.30793319]]), array([[0.08141962, 0.17954071],
       [0.10542797, 0.23903967],
       [0.15970772, 0.2348643 ]]), array([[0.065762  , 0.14822547],
       [0.15240084, 0.19728601],
     