In [1]:
import numpy as np
from Clasificador import ClasificadorNaiveBayes
from Datos import Datos

data = Datos('tic-tac-toe.data')
print(data.datos)
cl = ClasificadorNaiveBayes()

#Prueba de error
#print(cl.error(data.datos,2*np.ones(data.datos.shape[0])))

#Prueba de entrenamiento
cl.entrenamiento(data.datos,data.nominalAtributos,data.diccionario)
print(cl.entrenamientoAux)

#Prueba de test
clas = cl.clasifica(data.datos,data.nominalAtributos,data.diccionario)
print(clas)
print(cl.error(data.datos,clas))

[[2 2 2 ... 1 1 1]
 [2 2 2 ... 2 1 1]
 [2 2 2 ... 1 2 1]
 ...
 [1 2 1 ... 1 2 0]
 [1 2 1 ... 1 2 0]
 [1 1 2 ... 2 2 0]]
[array([[0.18975904, 0.22683706],
       [0.43975904, 0.30191693],
       [0.37048193, 0.47124601]]), array([[0.23493976, 0.27476038],
       [0.30421687, 0.3658147 ],
       [0.46084337, 0.35942492]]), array([[0.18975904, 0.22683706],
       [0.43975904, 0.30191693],
       [0.37048193, 0.47124601]]), array([[0.23493976, 0.27476038],
       [0.30421687, 0.3658147 ],
       [0.46084337, 0.35942492]]), array([[0.14457831, 0.17891374],
       [0.57831325, 0.23642173],
       [0.27710843, 0.58466454]]), array([[0.23493976, 0.27476038],
       [0.30421687, 0.3658147 ],
       [0.46084337, 0.35942492]]), array([[0.18975904, 0.22683706],
       [0.43975904, 0.30191693],
       [0.37048193, 0.47124601]]), array([[0.23493976, 0.27476038],
       [0.30421687, 0.3658147 ],
       [0.46084337, 0.35942492]]), array([[0.18975904, 0.22683706],
       [0.43975904, 0.30191693],
     