In [3]:
import numpy as np
from Clasificador import Clasificador
from Datos import Datos

data = Datos('german.data')
print(data.datos)
cl = Clasificador()

#Prueba de error
print(cl.error(data.datos,2*np.ones(data.datos.shape[0])))

[[0 6 4 ... 1 0 1]
 [1 48 2 ... 0 0 2]
 [3 12 4 ... 0 0 1]
 ...
 [3 12 2 ... 0 0 1]
 [0 45 2 ... 1 0 2]
 [1 45 4 ... 0 0 1]]
0.7
