In [25]:
from Clasificador import AlgoritmoGenetico
import numpy as np


ind1 = np.random.randint(2,size=(3*5))
print(ind1.reshape(3,5))
alg = AlgoritmoGenetico()


# ind2 = [0,1,1,1,0,0,1]

# inds = np.array([ind1,ind2])

sample = np.array([0,1])
alg.splitAtributos = [2,4]
alg.prior = 0

print(alg.prediceClase(ind1,sample))

[[1 1 1 1 1]
 [0 0 1 0 0]
 [1 1 1 1 0]]
[1 0]
0
